// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvWUCugBXVv7XDIWSnrn-YQxnfjohwPE',
    appId: '1:21022891122:web:99422149d94fc68915f6eb',
    messagingSenderId: '21022891122',
    projectId: 'fasum-c7522',
    authDomain: 'fasum-c7522.firebaseapp.com',
    storageBucket: 'fasum-c7522.appspot.com',
    measurementId: 'G-38CKPNEQ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYnVv47kfpxOjGszuRQst3Whf85FetxI',
    appId: '1:21022891122:android:b0ca8949a24b78d815f6eb',
    messagingSenderId: '21022891122',
    projectId: 'fasum-c7522',
    storageBucket: 'fasum-c7522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53sH8o4OkU9ByWsydFj1FrOs5QuiMnp8',
    appId: '1:21022891122:ios:8b6054d1d94c2c1215f6eb',
    messagingSenderId: '21022891122',
    projectId: 'fasum-c7522',
    storageBucket: 'fasum-c7522.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53sH8o4OkU9ByWsydFj1FrOs5QuiMnp8',
    appId: '1:21022891122:ios:08fb9897f693e9e415f6eb',
    messagingSenderId: '21022891122',
    projectId: 'fasum-c7522',
    storageBucket: 'fasum-c7522.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
